### ISSUE TITLE
install on moodle main branch (PHP 8.2) generates fatal error

### ISSUE THREAD

**Issue by danmarsden** [mattan-d/moodle-mod_stream#8]
Exception - Non-static method mod_stream\stream_video::call() cannot be called statically

line 32 of /mod/stream/settings.php: Error thrown
line 158 of /lib/classes/plugininfo/mod.php: call to include()
line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
line 8857 of /lib/adminlib.php: call to require()
line 22 of /admin/upgradesettings.php: call to admin_get_root()

**Comment by danmarsden** [comment]
also - if I fix that issue, I get the following errors during install because it triggers the curl call before being able to set the default values in the settings.php page.


Warning: Undefined property: stdClass::$apiendpoint in /mod/stream/locallib.php on line 96

Warning: Undefined property: stdClass::$accountid in mod/stream/locallib.php on line 99
Blocked /webservice/api/v2: The URL is blocked. [user 2]
line 111 of /lib/classes/event/url_blocked.php: call to debugging()
line 785 of /lib/classes/event/base.php: call to core\event\url_blocked->validate_before_trigger()
line 3962 of /lib/filelib.php: call to core\event\base->trigger()
line 3785 of /lib/filelib.php: call to curl->trigger_url_blocked_event()
line 4034 of /lib/filelib.php: call to curl->request()
line 109 of /mod/stream/locallib.php: call to curl->post()
line 32 of /mod/stream/settings.php: call to mod_stream\stream_video::call()
line 158 of /lib/classes/plugininfo/mod.php: call to include()
line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
line 8857 of /lib/adminlib.php: call to require()
line 22 of /admin/upgradesettings.php: call to admin_get_root()

Warning: Attempt to read property "status" on null in /www/moodle/mod/stream/settings.php on line 33

**Comment by mattan-d** [comment]
Hi @danmarsden,

Thank you for bringing these issues to our attention, and I appreciate your efforts in fixing the bugs.

Regarding the first issue with the error "Exception - Non-static method mod_stream\stream_video::call() cannot be called statically" on line 32 of /mod/stream/settings.php, I've made the necessary adjustments to ensure that the method call is properly handled as non-static. This should resolve the error you encountered.

For the second issue during installation, where warnings are triggered due to undefined properties and a blocked URL, I've revised the code logic to prevent the curl call from being triggered when the required properties such as $apiendpoint and $accountid are missing. This change should prevent the warnings and blocked URL during installation.

I've tested these fixes locally, and they seem to be working as expected. Please let me know if you encounter any further issues or if there's anything else I can assist you with.
